### ISSUE TITLE
FFmpeg support

### ISSUE THREAD

**Issue by m-ruhl** [dlueth/telerising.minimal#1]
Hey,

do I see it right, that ffmpeg is not included in the image and therefore `channels.m3u?ffmpeg=true` is not working?

If so, it should be at least noted in the README

**Comment by dlueth** [comment]
@m-ruhl ffmpeg is not included as it is not needed for telerising. Adding `ffmpeg=true` to the m3u-URL only changes the paths within the m3u to utilize ffmpeg which is handled by e.g. TVHeadEnd.
